 
 
  
    
CREATE TABLE categoria (
	codigo  int8 generated by default as identity,
	nome VARCHAR(50) NOT NULL,
	  primary key (codigo)
) ; 
 

 

INSERT INTO categoria (nome) values ('Tecnologia');
INSERT INTO categoria (nome) values ('Acessórios para veículos');
INSERT INTO categoria (nome) values ('Esporte e Lazer');
INSERT INTO categoria (nome) values ('Casa e Eletrodomésticos');
INSERT INTO categoria (nome) values ('Joias e Relógios'); 